version: '3.7'
services:
  mysqldb:
    image: mysql:latest
    restart: always
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=H2ow@ter
      - MYSQL_DATABASE=tododb
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - '3306:3306'
    networks:
      springboot-mysql-net:

  springboot-rest-service:
    image: k2infosoft/todo_springboot-demo:v1.0-release
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    networks:
      springboot-mysql-net:
    restart: always

networks:
  springboot-mysql-net:


