openapi: 3.0.1
info:
  title: Todo API
  description: API documentation for my Todo Spring Boot application
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local server
paths:
  /users:
    get:
      summary: Get all todos
      description: Returns a list of all todos
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Todo"
components:
  schemas:
    Todo:
      type: object
      properties:
        id:
          type: integer
          format: int64
        title:
          type: string
        description:
          type: string
        completed:
          type: boolean